### ISSUE TITLE
Search Nested Notes in `path_to_notes`

### ISSUE THREAD

**Issue by yihou** [Acidham/alfred-markdown-notes#7]
As per the title, just a suggestion if this can be done?

**Comment by Acidham** [comment]
I assume you mean notes in subfolders? 

There are a lot of post around that topic but I am not planning to implement due to the fact that search under python 2.7 would slow down search performance. Search performance is my first priority and with current implementation I can scale amount of notes up to 100k notes. With subfolder scanning it breaks with 1000 notes with just 100 subfolders. 

The usecase is also slightly different: md notes represents a flat notes repo and should not replace a document structure. Similar to to other md notes repos or databases.

**Comment by yihou** [comment]
I see your point there. How about `path_to_notes` supports comma separated value?

**Comment by Acidham** [comment]
For now only one path is supported,sry

**Comment by yihou** [comment]
Alright, no worries. I close it for now.
